src/carts/MagentoCartClient.js, src/carts/postCartEntry.js, src/common/serverless.yml, src/orders/MagentoOrderClient.js, test/carts/deleteBillingAddressTest.js, test/carts/deleteCartEntryIT.js, test/carts/deleteCartEntryTest.js, test/carts/deleteCouponIT.js, test/carts/deleteCouponTest.js, test/carts/getCartIT.js, test/carts/getShippingMethodsIT.js, test/carts/postBillingAddressTest.js, test/carts/postCartEntryIT.js, test/carts/postCartTest.js, test/carts/postCouponIT.js, test/carts/postCouponTest.js, test/carts/postPaymentIT.js, test/carts/postPaymentTest.js, test/carts/postShippingAddressTest.js, test/carts/postShippingMethodIT.js, test/carts/postShippingMethodTest.js, test/carts/putCartEntryIT.js, test/customer/postCustomerLoginTest.js, test/lib/addressITHelper.js, test/orders/postOrderIT.js, test/orders/postOrderTest.js
* updated default response codes, unit tests and ITs for CIF-167
=> CIF-333 - Implement default responses for POST & DELETE requests in Magento connector

src/carts/CartMapper.js, src/categories/CategoryMapper.js, src/products/ProductMapper.js, test/carts/CartMapperTest.js, test/carts/getCartIT.js, test/carts/postCartEntryIT.js, test/carts/putCartEntryIT.js, test/categories/CategoriesMapperTest.js, test/categories/getCategoriesIT.js, test/categories/getCategoriesTest.js, test/lib/requiredFields.js, test/orders/postOrderIT.js, test/products/ProductMapperTest.js, test/products/searchProductsIT.js
- renamed fields according to lastest API changes
=> CIF-346 - CIF API Cleanup: Data model naming in Magento implementation

src/carts/CartMapper.js, test/carts/CartMapperTest.js
- fixed bug detected when verifying this issue
=> CIF-372 - Update Magento implementation to follow the money value model

package-lock.json, package.json, src/carts/getShippingMethods.js, src/carts/postCartEntry.js, src/carts/putCartEntry.js, test/carts/deleteCartEntryIT.js, test/carts/deleteCouponIT.js, test/carts/deletePaymentIT.js, test/carts/deleteShippingAddressIT.js, test/carts/deleteShippingMethodIT.js, test/carts/getCartIT.js, test/carts/getShippingMethodsIT.js, test/carts/postCartEntryIT.js, test/carts/postCartTest.js, test/carts/postCouponIT.js, test/carts/postPaymentIT.js, test/carts/postShippingMethodIT.js, test/carts/putCartEntryIT.js, test/categories/getCategoriesIT.js, test/lib/addressITHelper.js, test/orders/postOrderIT.js, test/products/searchProductsIT.js
* Fix tests that check for error responses using chai 4.0.0
* Fixed bugs that were hidden by the not properly working tests
=> CIF-388 - Fix negative integration tests to properly check for failures

README.md
Fixed empty spaces
CIF-383
CIF-383
N/A
N/A
=> @trivial - fixed empty spaces in README.md

src/carts/postCartEntry.js, test/carts/getShippingMethodsTest.js, test/carts/postBillingAddressTest.js, test/carts/postCartEntryTest.js, test/carts/postShippingAddressTest.js, test/carts/postShippingMethodTest.js, test/carts/putCartEntryTest.js, test/lib/addressUTHelper.js, test/resources/sample-cart-empty.js, test/resources/sample-internal-server-error.js
Updated cart actions tests to improve coverage .
CIF-398
Quality improvement
Unit tests 
N/A
=> Cif 398 - Improve cart actions UT

src/products/ProductMapper.js, test/products/ProductMapperTest.js, test/products/searchProductsIT.js
Fixes category id type to String of product search results.
see CIF-422
Unit and Integration Tests
=> CIF 422 - fix category id type

ci/build.js, ci/deploy.js, customer-deployment/package.json, mocha-integration.json, mocha-unit.json, package-lock.json, package.json, src/carts/package-lock.json, src/carts/package.json, src/categories/package-lock.json, src/categories/package.json, src/common/deployment-install.js, src/common/package-lock.json, src/common/package.json, src/customer/package-lock.json, src/customer/package.json, src/orders/package-lock.json, src/orders/package.json, src/products/package-lock.json, src/products/package.json, test/lib/utils.js, test/package-lock.json, test/package.json
Some things we use are incompatible on platforms other than Mac and Linux. I changed the following things to make our project work also on Windows:
* Remove usage of `$(npm bin)`, except in the CI context
* Remove usage of environment variables in `package.json`. This was the case for Mocha test result files. I added config files instead and use a the `mocha-multi-reporters` plugin to beautify the test output in CI and locally.
* Fix files paths in `test/lib/utils.js`
* Fix EOL bug in `eslint-plugin-header`. Until https://github.com/Stuk/eslint-plugin-header/pull/17 is not merged yet, I point to my fork.
I executed `npm install` and `npm test` on Windows 10 via Powershell.
=> Cross Platform Support

test/carts/postCartPaymentIT.js, test/carts/postPaymentIT.js
=> CIF-370 - As a developer, I want to retrieve available payment methods for a shopping cart for Magento implementation

src/carts/MagentoCartClient.js, src/orders/MagentoOrderClient.js, src/orders/postOrder.js, test/carts/postShippingAddressTest.js, test/customer/postCustomerLoginIT.js, test/lib/config.js, test/orders/postOrderIT.js, test/orders/postOrderTest.js
Updated order implementation to handle customer cart endpoint. 
Fixed a small issue with customer cart create. 
Fixed post shipping address UTs.
CIF-433
CIF-433
UT, ITs, we retail
=> CIF-433 - updated order implementation for customer cart endpoint

ci/README.md
fixed small typo in ci/README 
CIF-371
CIF-371
Manual
=> @trivial CIF-371 - fixed README

src/carts/package-lock.json, src/carts/package.json, src/categories/package-lock.json, src/categories/package.json, src/common/package-lock.json, src/common/package.json, src/customer/package-lock.json, src/customer/package.json, src/orders/package-lock.json, src/orders/package.json, src/products/package-lock.json, src/products/package.json
Updated module packages.json to use latest released dependencies: api and common.
CIF-371
Preparation for release. 
UT and IT.
=> CIF-371 - updated dependencies to latest released version

src/carts/package.json, src/categories/package.json, src/customer/package.json, src/orders/package.json, src/products/package.json
Updated packages json to use first major release of commerce-cif-mageto-common.
CIF-371
CIF-371
IT / UT
=> @trivial CIF-371 - update packages.json to use first common mag maj rel

src/common/package.json
Updated dependencies for the common package so that the deployment install works for a released package. 
CIF-371
CIF-371
Manual tests: `npm pack` and `npm install <package>`
=> Cif 371 - fixed dependencies of released packages

src/carts/.npmignore, src/categories/.npmignore, src/common/.npmignore, src/common/package-lock.json, src/common/serverless.yml, src/customer/.npmignore, src/orders/.npmignore, src/products/.npmignore
Added `.npmignore` so we can exclude files that should not be part of released packages. 
CIF-371
CIF-371
Manual testing: `npm pack`
=> Cif 371 - exclude not need it files from released packages

src/carts/package.json, src/categories/package.json, src/customer/package.json, src/orders/package.json, src/products/package.json
Updated commerce-cif-magento actions to use the latest version of common.
CIF-371
CIF-371
=> CIF-371 - updated action packages with common release

package.json
Fix bug in Mocha configuration.
=> trivial - Fix Mocha configuration

.circleci/config.yml, .gitignore, ci/audit.js, ci/build.js, ci/ci.js, lerna.json, package-lock.json, package.json, src/carts/package-lock.json, src/categories/package-lock.json, src/common/package-lock.json, src/customer/package-lock.json, src/graphql/package-lock.json, src/orders/package-lock.json, src/products/package-lock.json, test/package-lock.json
* Add security audit
* Update to latest lerna version, since the current version didn't produce proper `package-lock.json` files
* Updated CI Docker image with npm 6.
We want to track security vulnerabilities as part of our project KPIs. This change creates a report as part of the build artifacts which can later be consumed by our KPI tracking tooling.
You can look at an example report here: https://387-137931347-gh.circle-artifacts.com/0/home/circleci/project/audit.json
For now, a high or critical vulnerability does not break the build. We need to decide on how to proceed here in the future.
The security audit is created during the build process and persisted as build artifact in CircleCi.
To create a security audit, run `npm run audit` and check the resulting `audit.json` file.
=> CIF-572 - Add NPM audit to CI

src/carts/CartMapper.js, src/products/ProductMapper.js, src/products/searchProducts.graphql, test/products/ProductMapperTest.js, test/products/getProductIT.js, test/products/getProductTest.js, test/resources/sample-product-search-single-product.js
Remove the TODO comment and add an explanation for why the stock information is hard-coded in the `CartMapper`
CIF-212
N/A
N/A
N/A
=> CIF-212 - [Magento] Inventory info in product model

customer-deployment/README.md
Update customer deployment readme to better explain the use of @latest vs. fixed version like @1.0.0 for customer bindings.
=> @trivial - update customer deployment readme

.circleci/config.yml, ci/docker-compose.yml, customer-deployment/serverless.yml, package.json, src/carts/serverless.yml, src/categories/serverless.yml, src/common/serverless.yml, src/customer/serverless.yml, src/graphql/serverless.yml, src/orders/serverless.yml, src/products/serverless.yml
See https://github.com/adobe/commerce-cif-common/pull/20.
=> CIF-684 - Upgrade Actions to NodeJS V10 runtime

customer-deployment/serverless.yml, src/customer/postCustomerAuth.js, src/customer/serverless.yml, test/customer/postCustomerAuthIT.js, test/customer/postCustomerAuthTest.js
CIF-473
Unit and integration tests.
- [ NA] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> CIF-473 - [Auth] Implement authorization endpoints for guest/anonymous login

src/customer/MagentoCustomerAuth.js, src/customer/postCustomerAuth.js, test/customer/postCustomerAuthIT.js, test/customer/postCustomerAuthTest.js
- return auth token as defined in CIF API
CIF-474
Added integration and unit tests.
- [ NA] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> CIF-474 - [Auth] Implement authorization endpoints for user login

src/common/MagentoClientBase.js, src/customer/MagentoCustomerAuth.js, test/categories/getCategoriesIT.js, test/common/MagentoClientBaseTest.js, test/customer/getCustomerByIdIT.js, test/customer/getCustomerByIdTest.js, test/customer/postCustomerAuthTest.js, test/lib/config.js, test/orders/postOrderIT.js
CIF-475
Updated unit and integration tests.
- [ NA] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> CIF-475 - [Auth] Change Magento implementation to use authorization tokens

customer-deployment/serverless.yml, src/common/MagentoClientBase.js, src/customer/MagentoCustomer.js, src/customer/MagentoCustomerAuth.js, src/customer/getCustomer.js, src/customer/serverless.yml, test/customer/getCustomerIT.js, test/customer/getCustomerTest.js
CIF-691
Unit and integration tests.
- [NA] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> CIF-691 - /customers/{id} should be deprecated and replaced by /customers/me

ci/audit.js, ci/ci.js
- temporary fix for intermittent failure
=> CIF-694 - NPM Audit seems to randomly fail on circleCI

README.md, ci/README.md, customer-deployment/README.md, package.json, src/carts/package.json, src/categories/package.json, src/common/package.json, src/customer/README.md, src/customer/package.json, src/graphql/package.json, src/orders/package.json, src/products/package.json, test/package.json
See https://github.com/adobe/commerce-cif-api/pull/53.
=> CIF-736 - Rename CIF to CIF REST

package-lock.json, package.json
Fix GitHub and `npm audit` security alerts for this projects.
=> CIF-678 - fix security alerts

customer-deployment/serverless.yml, src/carts/serverless.yml, src/categories/serverless.yml, src/common/serverless.yml, src/customer/serverless.yml, src/orders/serverless.yml, src/products/serverless.yml
- increased all actions concurrency to 200
=> CIF-1015 - [Magento] Increase concurrency parameter of all actions
